<!--Initial Release-->
<!--Use Beautify Extension-->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!--tag to make IE use its modern rendering engine-->
    <title>Asset Redirect</title>
</head>

<body>
    <p id="title">Asset Redirect</p>
    <p>Display Related Assets Links by using the Asset Number and SiteID</p>
    <p id="result"></p>
    <!--    thing for results output, this text will be filled using javascript below-->
    <p>Links for other Assets can be generated by filling in the information below</p>
    <!--    the input fields are in a table so it aligns better-->
    <table>
        <tr>
            <td id="col1">
                <p>Site ID:</p>
            </td>
            <td id="col2">
                <!--    drop down menu for site selector        -->
                <select id="siteName">
                    <option value="BA">BA: Calgary</option>
                    <option value="CA">CA: Kankakee</option>
                    <option value="GA">GA: Wilmington</option>
                    <option value="GC">GC: Sumas</option>
                    <option value="GE">GE: Ashcroft</option>
                    <option value="GH">GH: Hawkesbury</option>
                    <option value="GI">GI: Madoc</option>
                    <option value="GK">GK: IG Brampton</option>
                    <option value="GR">GR: BramCal</option>
                    <option value="GS">GS: Sylacauga</option>
                    <option value="GV">GV: Texas/Southwest</option>
                    <option value="PBM">PBM: Senica/Sloviakia</option>
                </select>
            </td>
        </tr>
        <tr>
            <td id="col1">
                <p>Asset Number:</p>
            </td>

            <td id="col2">
                <!--Input box & dropdown for asset number-->
                <div id="AssetNum"><input type="text" id="assetNum" oninput="buttonEnable()"></div>
            </td>

            <td id="col4">
                <!--a tool tip hidden in a question mark-->
                <button id="submitNum" disabled=true onclick="genLinks()">Generate</button>
                <!--    the submit button, defaults to disabled-->
            </td>
        </tr>
    </table>
</body>

<script type="application/javascript">
    var start;

    //this calls the button enable function when the asset number is changed

    function checkValid() {
        var patt = new RegExp("[A-Z][0-9]{4}"); //check if input is right format
        var str = assetNum.value.toUpperCase();
        var result = patt.test(str);
        if (result == true && str.length == 5) {
            assetNum.value = str;
            return true;
        } else {
            return false;
        }
    }

    function buttonEnable() { //enable the button when a valid asset number is inputted

        if (checkValid()) {
            document.getElementById("submitNum").disabled = false;
            console.log("enable");
        } else {
            document.getElementById("submitNum").disabled = true;
            console.log("disable");
        }
    }

    function genLinks() { //loops through the assets and output rows in array with the right asset number

        //        http://nscandacmaxapp1.na.iko/maximo/ui/login?mobile=false&event=loadapp&value=createsr&additionalevent=insert&additionaleventvalue=assetnum=H1963
        //        http://nscandacssrs1/ReportServer?/Maximo/Asset%20Spare%20Parts&paramSiteID=GS&paramAssetNum=C7102
        //        http://operations.connect.na.local/support/Reliability/ReliabilityShared/Pages/AssetFinder2.aspx?cheese=GH=&cheeseNum=S2010=&mobile=0

        console.log("generating links");
        var assetN = assetNum.value;
        var siteID = siteName.value;
        var text = "<ul>"; //gonna make a list
        //add blue link
        text += "<li id=\"blueLink\"><a href=\"http://nscandacmaxapp1.na.iko/maximo/ui/login?mobile=false&event=loadapp&value=createsr&additionalevent=insert&additionaleventvalue=assetnum=" + assetN + "\">" + assetN + ": Create Service Request (In Maximo)" + "</a></li>";
        //add red link
        text += "<li id=\"redLink\"><a href=\"http://nscandacssrs1/ReportServer?/Maximo/Asset%20Spare%20Parts&paramSiteID=" + siteID + "&paramAssetNum=" + assetN + "\">" + assetN + ": Go To Spare Parts List" + "</a></li>";

        text += "<li id=\"purpleLink\"><a href=\"http://operations.connect.na.local/support/Reliability/ReliabilityShared/Pages/AssetFinder2.aspx?cheese=" + siteID + "=&cheeseNum=" + assetN + "=&mobile=0\">" + assetN + ": Asset Finder" + "</a></li>";

        text += "</ul>";
        document.getElementById("result").innerHTML = text;
    }

    document.addEventListener('DOMContentLoaded', function() { //set to siteID equal to the variable in the URL ...?cheese=GK case insensitive
        //this runs as soon as the site has been loaded
        var paraURL = window.location.search
        if (paraURL.indexOf("cheese") != -1) {
            var cheese = paraURL.split('=')[1]; //get siteID
            siteName.value = cheese.toUpperCase();
        }
        if (paraURL.indexOf("cheeseNum") != -1) {
            var cheeseNum = window.location.search.split('=')[3]; //get assetNum
            assetNum.value = cheeseNum.toUpperCase();
        }

        if (window.innerHeight > window.innerWidth) {
            document.getElementById("result").innerHTML = "This Page is best viewed in landscape mode";
        }
        //call function for generating links
        if (checkValid()) {
            document.getElementById("submitNum").disabled = false;
            genLinks();
        }
    }, false);
</script>

<style>
    /*CSS for formatting stuff*/

    /*CSS for the links add to here when new links are added*/

    #blueLink {
        border-style: solid;
        border-width: medium;
        border-color: blue;

    }

    #redLink {
        border-style: solid;
        border-width: medium;
        border-color: red;
    }

    #purpleLink {
        border-style: solid;
        border-width: medium;
        border-color: sandybrown;
    }

    /*don't touch below*/

    a {
        display: block;
    }

    /*    makes the hyperlink clickable within the box*/

    li {
        padding: 5px;
        width: 80%;

    }

    .p {
        padding: 0;
        margin: 0;
    }

    body {
        font-family: "Sans-serif";
        font-size: 2em;
        display: inline-table;
        width: 95%;
    }

    input {
        font-family: "Sans-serif";
        font-size: 0.9em;
        width: 90%;
    }

    select {
        font-family: "Sans-serif";
        font-size: 0.9em;
        width: 90%;
    }

    table {
        vertical-align: top;
        width: 95%
    }

    button {
        font-family: "Sans-serif";
        font-size: 0.9em;
    }

    #title {
        text-align: center;
        font-size: 2em;
        margin-top: 0px;
        margin-bottom: 0px;
    }

    #col1 {
        padding-right: 0;
        width: 40%;
    }

    #col2 {
        padding-left: 0%;
        width: 55%;
    }

    #col3 {
        padding-left: 0%;
        padding-right: 5%;
        width: 55%;
        text-align: right;
    }

    #col4 {
        padding-left: 0%;
        width: 5%;
    }

</style>

</html>